<div class="wrap bem-zf_core-admin">
    <div id="icon-options-general" class="icon32">
        <br/>
    </div>
    <h2>Настройки плагина</h2>
</div>

<div class="brx-options_form" data-view="brx.OptionsForm" data-scope="" data-prefix="brx_SearchGoogle" style="display: none;">
    <div class="form_fields">
        <div class="form_field fullsize field_se_id" data-attach-point="fields.se_ID">
            <label class="">Идентификатор вашей поисковой системы</label>
            <span class="form_field-input_box"><input name="se_ID" type="text" value=""/></span>
            <div class="form_field-tips"><a href="">Управление поисковой системой на сайте google</a></div>
        </div>
        <div class="form_field stretch field_show_input" data-attach-point="fields.show_input">
            <label class="width45">Отображать строку ввода:</label>
            <span class="form_field-input_box">
                <select name="show_input">
                    <option value="1">Да</option>
                    <option value="1">Нет</option>
                </select>
            </span>
            <div class="form_field-tips"></div>
        </div>
    </div>
    <div class="button_pane">
        <button class="button button-large button-primary" data-attach-event="saveOptions">Сохранить</button>
    </div>
    <script type="text/javascript">
        (function($){
            var input = $('.field_se_id input');
            var href = $('.field_se_id a');
            input.change(function(){
                var val = input.val();
                if(!val){
                    href.hide();
                }else{
                    href.attr('href', 'https://www.google.com/cse/setup/basic?cx='+val).show();
                }
            }).change();
        }(jQuery));
    //    window.setupOptions = <?php //echo JsonHelper::encode($this->options);?>;
    </script>
</div>
